version: "3.6"
services:
  counter:
    build:
      context: .
    restart: always
    image: simple-counter:1.0.0
    depends_on:
    - postgres
    ports:
    - '8080:8080'

  postgres:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: counter
      POSTGRES_PASSWORD: simplecounter
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
