version: "3.6"
services:
  counter:
    build:
      context: .
    restart: always
    image: simple-counter:1.0.0
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    depends_on:
    - postgres
    ports:
    - '172.17.0.1:8080:8080'
  purge_token:
    build:
      context: .
    restart: always
    image: simple-counter:1.0.0
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    depends_on:
    - postgres
    command:
    - scripts/purge_token.py

  web:
    build:
      context: web
    restart: always
    image: simple-counter-web:1.0.1
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - '172.17.0.1:8081:3000'

  postgres:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: counter
      POSTGRES_PASSWORD: simplecounter
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
